genrelist = {"Acoustic Pop": ["One in a Million", "Stuck", "Missing U", "Turtle",
                              "Like a fool", "Wonderful Day", "Someone Like Me", "Say Yes"],
             "Adult Contemporary": ["The Reason Why"],
             "Ballad": ["Be as One", "Wishing", "Promise", "After Moon", "Rewind", "21:29", "The Reason Why"],
             "Power Ballad": ["Cactus"],
             "Latin pop": ["Hell in Heaven", "Firework", "1,3,2", "Last Waltz", "Three Times A Day"],
             "Rock": ["Stuck in my head", "Don't Call Me Again"],
             "Beach Rock": ["HO!"],
             "Soft Rock": ["Ponytail"],
             "Pop Rock": ["Cactus"],
             "Funk": ["Ding Dong", "WoW", "Changing!", "Turn it Up", "Scientist"],
             "Funk Pop": ["HOT"],
             "Brit Funk": ["Rainbow"],
             "Electro Funk": ["Love Foolish", "Fake & True"],
             "Contemporary R&B": ["Cry For Me", "21:29", "Handle It", "After Moon", "Say Yes",
                                  "Thank You, Family", "Doughnut"],
             "New Jack Swing": ["Sweet Summer Day"],
             "Bossa Nova": ["Alcohol-Free", "Jaljayo Good Night"],
             "March": ["Funfare", "Stuck in my head", "Shot Clock", "Touchdown", "WooHoo", "Dejavu"],
             "Neo Soul": ["Ice cream", "TBTIED", "After Moon", "1 to 10", "Wonderful Day"],
             "Smooth Soul": ["Doughnut"],
             "Pop Soul": ["I Want You Back", "Tuk Tok", "Touchdown"],
             "Chillout-lounge": ["Jaljayo Good Night", "Handle It", "Someone Like Me", "Doughnut", "Up no more"],
             "Disco": ["The Feels", "Moonlight", "Turn it up"],
             "Disco House": ["Real You", "Changing!", "Precious Love", "Espresso"],
             "Disco Pop": ["Cruel", "F.I.L.A.", "Push & Pull"]
             }


genreMenu = [
    ("Ballad", ["Power Ballad"]),
    ("Bossa Nova", ["Latin Pop"]),
    ("Rock", ["Beach Rock", "Soft Rock", "Pop Rock"]),
    ("Funk", ["Funk Pop", "Brit Funk", "Electro Funk"]),
    ("Seasonal Music", ["Tropical", "Winter Song"]),
    ("Soul", ["Neo Soul", "Smooth Soul", "Pop Soul", "Chillout-lounge"]),
    ("Contemporary RnB", ["New Jack Swing"]),
    ("Disco", ["Disco House", "Disco Pop"]),
    ("March", []),
    ("Synthwave", []),
    ("Future Funk", []),
    ("Trap", []),
    ("Trance", []),
    ("Pop", ["Acoustic Pop", "City Pop", "Synth Pop", "Retro Pop", "Indie Pop", "Electro Pop",
             "Dance Pop", "Color Pop", "Bubblegum Pop", "Latin Pop", "Funk Pop"]),
    ("Acoustic Pop", ["Adult Contemporary"]),
    ("EDM", ["Future House", "Future Bass", "Dubstep", "Electro bounce"])
]
