# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracking_timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
from musicshowtracker import MusicShow

# --------------- initialize music tracker time duration ------------------- #
inkigayo = MusicShow("INK")
music_bank = MusicShow("MUB")
now_date = datetime.now()
DURATION_INT1 = int((inkigayo.end_day_local.replace(tzinfo=None) - now_date).total_seconds())
DURATION_INT2 = int((music_bank.end_day_local.replace(tzinfo=None) - now_date).total_seconds())


def conv_secs(secs: int):
    days = secs//86400
    hours = (secs - days*86400)//3600
    minutes = (secs - days*86400 - hours*3600)//60
    seconds = secs - days*86400 - hours*3600 - minutes*60
    minsec = f'{days:02}:{hours:02}:{minutes:02}:{seconds:02}'
    return minsec


# class Ui_Form(object):
class UiForm(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.countdown1 = None
        self.countdown2 = None
        self.label = None
        self.label_2 = None

        self.time_left_int1 = 0
        self.time_left_int2 = 0
        self.myTimer = QtCore.QTimer(self)

    # App window
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 300)
        self.countdown1 = QtWidgets.QLabel(Form)
        self.countdown1.setGeometry(QtCore.QRect(160, 100, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(37)
        self.countdown1.setFont(font)
        self.countdown2 = QtWidgets.QLabel(Form)
        self.countdown2.setGeometry(QtCore.QRect(160, 200, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(37)
        self.countdown2.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 170, 401, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.update_gui()
        self.startTimer()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Music Show Tracker"))
        self.label_2.setText(_translate("Form",
                                        "   DAYS                  HOURS                MINUTES              SECONDS"))

    def startTimer(self):
        self.time_left_int1 = DURATION_INT1
        self.time_left_int2 = DURATION_INT2

        self.myTimer.timeout.connect(self.timerTimeout)
        self.myTimer.start(1000)

    def timerTimeout(self):
        self.time_left_int1 -= 1
        self.time_left_int2 -= 1

        if self.time_left_int1 == 0:
            self.time_left_int1 = DURATION_INT1

        if self.time_left_int2 == 0:
            self.time_left_int2 = DURATION_INT2

        self.update_gui()

    def update_gui(self):
        minsec1 = conv_secs(self.time_left_int1)
        minsec2 = conv_secs(self.time_left_int2)
        self.countdown1.setText(minsec1)
        self.countdown2.setText(minsec2)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
